### ISSUE TITLE
Humanizing a string with PascalCase and _ in it

### ISSUE THREAD

**Issue by simoneb** [MehdiK/Humanizer#398]
Hello, it looks like the `.Humanize()` method does not handle strings containing a mix of PascalCase and underscores:

```cs
"HelloWorld_World".Humanize() // "HelloWorld World"
```

Whereas I would expect `Hello world world`

**Comment by MehdiK** [comment]
Thanks for submitting the issue @simoneb. That's kinda the expected behavior at least in this very specific context!! Humanizer was born out of [BDDfy](https://github.com/TestStack/TestStack.BDDfy) framework and in BDDfy when there's underscore in the method name only underscores are removed. This is to give full control over what gets humanized so if you want `HelloWorld world` you can get it, and if you really want `Hello world world` all it takes is to call `Humanize` again!

**Comment by simoneb** [comment]
> if you really want Hello world world all it takes is to call Humanize again

That's quite a good point actually, I didn't think of it!

**Comment by MehdiK** [comment]
I might also add that Humanizers is just a bunch of extension methods. If you need to change the behavior of a method or make it smarter you can just wrap it in your extension method. In this particular case you could create a wrapper, I don't know - perhaps `FreakingHumanize` ;), that calls Humanize twice!

**Comment by jnm2** [comment]
Rather than call `.Humanize().Humanize()`, I think it's way clearer to state what you want: `.Humanize().Transform(To.SentenceCase)`.
