### ISSUE TITLE
CultureInfo doesn't work properly in DateTime Humanize

### ISSUE THREAD

**Issue by mahdi** [MehdiK/Humanizer#407]
I'm using DateTime Humanize and works just fine on my local dev machine but when I deploy it on the server it always shows it in English. I've tried setting CultureInfo in Web.config, ViewPage and the Humanize method and got no result. This is an ASP.NET MVC app with old ASPX view engine.

**Comment by MehdiK** [comment]
I think this is more of a StackOverflow question than Humanizer. Humanizer doesn't do anything special with Culture. It [asks for the `CurrentUICulture`](https://github.com/MehdiK/Humanizer/blob/master/src/Humanizer/Configuration/LocaliserRegistry.cs#L49) and everything flows on from there. Maybe you're setting the culture instead of uiCulture?

**Comment by mahdi** [comment]
I'm sure nothing's wrong in code because it's working on dev machine. I guess something's wrong with the Culture setting on the server machine. Any idea?

**Comment by MehdiK** [comment]
What does the globalization section of your Web config look like?

**Comment by mahdi** [comment]
<globalization culture="fa-IR" enableClientBasedCulture="false" requestEncoding="UTF-8" responseEncoding="UTF-8" uiCulture="fa-IR" />

**Comment by MehdiK** [comment]
That config looks good. I'm not sure what's happening to the culture on the server!

I'm afraid I have to close this issue as it's not related to Humanizer.
