### ISSUE TITLE
TimeSpan.FromMinutes(50).Humanize(2, null, TimeUnit.Hour, TimeUnit.Minute) is "1 hour, 50 minutes"

### ISSUE THREAD

**Issue by GeoffArmstrong** [MehdiK/Humanizer#434]
Obviously this is wrong. `TimeSpan.FromMinutes(50).Humanize(2)` gives the correct `"50 minutes"`.

**Comment by MehdiK** [comment]
Thanks for reporting the problem @GeoffArmstrong. We will try to fix this in the near future. If you have fixed it or would like to do it, please send us a PR and we will merge after review.

**Comment by GeoffArmstrong** [comment]
Thanks! :)

**Comment by jeremysimmons** [comment]
Also having this issue. Humanizer.Localisation.ResourceKeys.TimeSpanHumanize GetResourceKey doesn't support Humanizer.Localisation.Tense the way that DateHumanize does.
Should TimeSpanHumanize support Tense?

**Comment by MehdiK** [comment]
I don't think so @jeremysimmons. `TimeSpan` is not bound to time tense: it's just how long it is without any indication of when; e.g. `TimeSpan.FromMinutes(2)` doesn't say whether it's 2 minutes in the future or in the past: it's just 2 minutes!

**Comment by jeremysimmons** [comment]
@MehdiK the CLR documentation indicates that it does have directionality. https://msdn.microsoft.com/en-us/library/system.timespan(v=vs.110).aspx - A TimeSpan object represents a time interval (duration of time or elapsed time) that is measured as a positive or negative number of days, hours, minutes, seconds, and fractions of a second.

I would say that in most common case, a developer needs the quantity without the sign, but there may be times when they explicitly need the sign.

For now, can the code be patched so that TimeSpans representing a negative quantity will not cause an exception?

I have a changeset I would like to contribute for that fix.

**Comment by ofirgeller** [comment]
Similar problem where a 52 minutes time span becomes 1 hour when max unit is hour.
ts.Humanize(maxUnit: TimeUnit.Hour); // becomes 1 hour.

**Comment by GeoffArmstrong** [comment]
Thanks for the fix!

**Comment by MehdiK** [comment]
The fix for this is now released to NuGet as v1.37.7.
